<?xml version="1.0" encoding="utf-8"?><Database Name="Clinic" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-Q8HD199;Initial Catalog=Clinic;Integrated Security=True" SettingsObjectName="MedicalClinic.Properties.Settings" SettingsPropertyName="ClinicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Appointment" Member="Appointment">
    <Type Name="Appointment">
      <Column Name="Id_Appointment" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date_Appointment" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Id_Doctor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Receptionist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descirption" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="Diagnosis" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="Id_Patient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Association Name="Appointment_Examination_Laboratory" Member="Examination_Laboratory" ThisKey="Id_Appointment" OtherKey="Id_Appointment" Type="Examination_Laboratory" />
      <Association Name="Appointment_Examination_Physical" Member="Examination_Physical" ThisKey="Id_Appointment" OtherKey="Id_Appointment" Type="Examination_Physical" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="Id_Patient" OtherKey="Id_Patient" Type="Patient" IsForeignKey="true" />
      <Association Name="Staff_Appointment" Member="Staff" ThisKey="Id_Doctor" OtherKey="Id_Staff" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Appointment1" Member="Staff1" ThisKey="Id_Receptionist" OtherKey="Id_Staff" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exam_Dictionary" Member="Exam_Dictionary">
    <Type Name="Exam_Dictionary">
      <Column Name="Exam_Code" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Exam_Dictionary_Examination_Laboratory" Member="Examination_Laboratory" ThisKey="Exam_Code" OtherKey="Exam_Code" Type="Examination_Laboratory" />
      <Association Name="Exam_Dictionary_Examination_Physical" Member="Examination_Physical" ThisKey="Exam_Code" OtherKey="Exam_Code" Type="Examination_Physical" />
    </Type>
  </Table>
  <Table Name="dbo.Examination_Laboratory" Member="Examination_Laboratory">
    <Type Name="Examination_Laboratory">
      <Column Name="Id_Examination" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comments_Doctor" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="Date_Of_Order" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Exec_Cancel" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comments_Man_Lab" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="Date_Conf_Cancel" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Man_Lab" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Analyst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Appointment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Exam_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Appointment_Examination_Laboratory" Member="Appointment" ThisKey="Id_Appointment" OtherKey="Id_Appointment" Type="Appointment" IsForeignKey="true" />
      <Association Name="Exam_Dictionary_Examination_Laboratory" Member="Exam_Dictionary" ThisKey="Exam_Code" OtherKey="Exam_Code" Type="Exam_Dictionary" IsForeignKey="true" />
      <Association Name="Staff_Examination_Laboratory" Member="Staff" ThisKey="Id_Analyst" OtherKey="Id_Staff" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Examination_Laboratory1" Member="Staff1" ThisKey="Id_Man_Lab" OtherKey="Id_Staff" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Examination_Physical" Member="Examination_Physical">
    <Type Name="Examination_Physical">
      <Column Name="Id_Examination" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="Exam_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Appointment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Appointment_Examination_Physical" Member="Appointment" ThisKey="Id_Appointment" OtherKey="Id_Appointment" Type="Appointment" IsForeignKey="true" />
      <Association Name="Exam_Dictionary_Examination_Physical" Member="Exam_Dictionary" ThisKey="Exam_Code" OtherKey="Exam_Code" Type="Exam_Dictionary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patient">
    <Type Name="Patient">
      <Column Name="Id_Patient" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PESEL" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointment" ThisKey="Id_Patient" OtherKey="Id_Patient" Type="Appointment" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staff">
    <Type Name="Staff">
      <Column Name="Id_Staff" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="Staff_Appointment" Member="Appointment" ThisKey="Id_Staff" OtherKey="Id_Doctor" Type="Appointment" />
      <Association Name="Staff_Appointment1" Member="Appointment1" ThisKey="Id_Staff" OtherKey="Id_Receptionist" Type="Appointment" />
      <Association Name="Staff_Examination_Laboratory" Member="Examination_Laboratory" ThisKey="Id_Staff" OtherKey="Id_Analyst" Type="Examination_Laboratory" />
      <Association Name="Staff_Examination_Laboratory1" Member="Examination_Laboratory1" ThisKey="Id_Staff" OtherKey="Id_Man_Lab" Type="Examination_Laboratory" />
    </Type>
  </Table>
</Database>